apiVersion: v1
kind: Namespace
metadata:
  name: my-app-namespace

---
apiVersion: v1
kind: Pod
metadata:
  name: pos-app-pod
  namespace: my-app-namespace
  labels:
    app: pos-app
spec:
  containers:
  - name: node-app-container
    image: jeromejay09/demo-app:pos-1.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  imagePullSecrets:
    - name: my-registry-secret


---
apiVersion: v1
kind: Service
metadata:
  name: pos-app-service
  namespace: my-app-namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: pos-app

